# Generated by Django 5.0.3 on 2024-03-28 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hostel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stu_name', models.CharField(max_length=20)),
                ('father_name', models.CharField(max_length=20)),
                ('mother_name', models.CharField(max_length=20)),
                ('name_of_admitted_course', models.CharField(max_length=30)),
                ('name_of_hostel', models.CharField(choices=[('Savitribai Phule', 'Savitribai Phule'), ('Regency Hostel', 'Regency Hostel'), ('Blue Star Hostel', 'Blue Star Hostel')], max_length=20)),
                ('category', models.CharField(choices=[('OBC', 'OBC'), ('SC', 'SC'), ('ST', 'ST'), ('GEN', 'GEN')], max_length=10)),
                ('date_of_birth', models.DateField()),
                ('father_phone_no', models.IntegerField()),
                ('stu_email', models.EmailField(max_length=254)),
            ],
        ),
    ]
